### ISSUE TITLE
DESIGN file is corrupted

### ISSUE THREAD

**Issue by divinity76** [mtuomi/SecondReality#4]
im fairly certain the DESIGN file is corrupted, line 5 and 6 currently says

```- Setup screeni grafiikkatilaan, joka n„ytt„„ tekstilt„
- Kun stuhvit valittu, lent„„ polygoniface kohti katsojaa muuttaen
```  

and see

```"       Code by ...
	
	jyrin„ ns. t„ysill„
	suuri vektorialus lent„„ yli, pohjassa erikoisdetailia
	500 polygonia
	lent„„ horisonttiin lujaa
	v„l„ht„„ rengasvallina, kuten Startrek VI:n alussa Praxis
	v„l„hdys kasvaa ja lent„„ kohti katsojaa (surround)
	ruutu v„l„ht„„
```
 -  seemingly some some program did not understand the character encoding that was in use, and just replaced all characters it didn't understand with `„`  

(if you have the originals somewhere, and need help converting them properly to UTF-8 from whatever encoding its in, please let me know!)

**Comment by mtuomi** [comment]
Thanks, fixed now
