### ISSUE TITLE
God of Assembly

### ISSUE THREAD

**Issue by j1m1l0k0** [mtuomi/SecondReality#5]
God of Assembly 💃

**Comment by antdude** [comment]
Is that an issue? :P

**Comment by j1m1l0k0** [comment]
@antdude  No, compliment :P

**Comment by antdude** [comment]
:P

**Comment by j1m1l0k0** [comment]
@Are you an assembly programmer too?

**Comment by antdude** [comment]
I assume me and not "are" user. No, I don't even code. I just like watching demos. :)

**Comment by j1m1l0k0** [comment]
Ok ;)

**Comment by ignlg** [comment]
I used x86 asm when I was a pre-teen (demoscene stuff, even a videogame) and have to join this compliment: **This is a masterpiece.** I miss asm a lot! Good old days, arrr! P-)
`jmp begin`

**Comment by j1m1l0k0** [comment]
It really was a time of much learning and undeground: P @ignlg
